hosts: uf
  gather_facts: True
  become: True
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - copy:
        src: /home/ubuntu/myplatform/datetime.xml
        dest: /opt/splunkforwarder/etc/
        owner: splunk
        group: splunk
        mode: 0755
    - name: perform restart on UFs
      shell: /opt/splunkforwarder/bin/splunk restart
      become: true
      become_user: splunk
- hosts: hf
  gather_facts: True
  become: True
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - copy:
        src: /home/ubuntu/myplatform/datetime.xml
        dest: /opt/splunk/etc/
        owner: splunk
        group: splunk
        mode: 0755
    - name: perform  restart on HFs
      shell: /opt/splunk/bin/splunk restart
      become: true
      become_user: splunk
